# Generated by Django 4.2.1 on 2023-06-26 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_alter_producto_fecha_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_ingreso',
        ),
    ]
